require File.expand_path(File.dirname(__FILE__) + '/lib/antfarm/version')

Gem::Specification.new do |s|
  s.name          = %q{antfarm}
  s.version       = "#{Antfarm.version}"
  s.authors       = ['Bryan T. Richardson']
  s.email         = %q{btricha@sandia.gov}
  s.date          = Time.now.strftime('%Y-%m-%d')
  s.summary       = %q{Passive network mapping tool}
  s.description   = %q{ANTFARM is a passive network mapping tool capable of
                       parsing data files generated by common network
                       administration tools, network equipment configuration
                       files, etc. Designed for use when assessing critical
                       infrastructure control systems.}
  s.homepage      = %q{https://github.com/ccss-sandia/antfarm}
  s.files         = Dir['{bin,lib,man}/**/*','README.md'].to_a
  s.require_paths = ['lib']
  s.executables  << 'antfarm'
  s.has_rdoc      = false

  s.add_dependency 'activerecord',   '= 4.1.8'
  s.add_dependency 'ipaddress',      '= 0.8.0'
  s.add_dependency 'launchy',        '= 2.1.2'
  s.add_dependency 'packetfu',       '= 1.1.6'
  s.add_dependency 'pg',             '= 0.17.1'
  s.add_dependency 'pry',            '= 0.9.12'
  s.add_dependency 'ruby-graphviz',  '= 1.2.1'
  s.add_dependency 'slim',           '= 2.0.2'
  s.add_dependency 'terminal-table', '= 1.4.5'
  s.add_dependency 'trollop',        '= 2.0'
end
